#!/bin/sh

docker run --rm -it -w /current \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v $HOME/.ssh:/.ssh \
  -v $(pwd):/current \
  -v gcloud-data:/.config \
  -v gcloud-data:/.kube \
  -v gcloud-data:/.kubecfg \
  -p 10443:10443 \
  -p 10080:10080 \
  --name kubectl \
  yurifl/gcloud kubectl $@

