#!/bin/sh

docker run --rm -it -w /current \
  -v gcloud-data:/.config \
  -v gcloud-data:/.kube \
  -v gcloud-data:/.kubecfg \
  -p 5432:5432 \
  yurifl/gcloud bash

# yurifl/gcloud kubectl port-forward v2-database-keeper-0 --namespace=database 5432:5432
